### ISSUE TITLE
Build errors using InterpolatedLookupTable 

### ISSUE THREAD

**Issue by SchrodingerNZ** [savant-nz/carbon#11]
Code previously using InterpolatedLookupTables correctly now fail to build, citing casting and syntax errors

**Comment by McMassiveNZ** [comment]
#14 Should be the fix

**Comment by richard-viney** [comment]
Fixed by https://github.com/savant-nz/carbon/commit/fa29cd40ba8c708bde4e0073db0ce77530abccbb
