### ISSUE TITLE
Current Apple SDKs are not supported

### ISSUE THREAD

**Issue by SchrodingerNZ** [savant-nz/carbon#12]
Carbon has fallen out of compatability with current Apple SDKs, updates are needed to allow building the SDK on that platform, and for projects utilising Carbon to build for iOS platforms

**Comment by richard-viney** [comment]
Fixed in fa29cd40ba8c708bde4e0073db0ce77530abccbb...7d35efd8a93322e03ab3e312be60cc42deb7dd67
