### ISSUE TITLE
Issues building on MacOS Windows and Linux Platforms

### ISSUE THREAD

**Issue by McMassiveNZ** [savant-nz/carbon#13]
I've tried to build the dependencies on Windows, Linux and MacOS and all fail citing some obscure errors deep within SConstruct or Ruby. I suggest using a less complex and obscure build system like CMake and a cross platform package manager like VCPkg for dependencies.

- When trying to build for MacOS Ruby tells me it can't find Xcode despite it being installed and up to date on my system.
- When trying to build for iOS AngelScript fails with a whole host of compile errors.
- Linux seems to be able to build the dependencies albeit with a tonne of warnings but calling ruby Scripts/RunApplication.rb BoxesSample produces this error

```
File "/home/.../carbon/Source/SConscript", line 199

    AddPostAction(installedTarget, ChMod(str(installedTarget), 0755)

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by richard-viney** [comment]
Fixed in fa29cd40ba8c708bde4e0073db0ce77530abccbb...7d35efd8a93322e03ab3e312be60cc42deb7dd67
